default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: toriapp_development
  template: template0

test:
  <<: *default
  database: toriapp_test

production:
  <<: *default
  database: toriapp_production
  username: toriapp
  password: <%= ENV['TORIAPP_DATABASE_PASSWORD'] %>
