# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 58cd2fa0bf43a6f579dbd2bcf6c3a345b9b96ef06877a0fdc00763c3ea372905840d0212abab67bddf283cf0c1e324db3c29e4830fd3dfa63993d50aec738773

test:
  secret_key_base: 301fbcb04bb341161ad6a01c74ae8fc3bad401b22817fff4f3683f1993af52400e8fe8f3b73ebbba7566a9fcb72991a0930558b4cde15321bd6ca0136bd1472a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
